---
editor_options: 
  markdown: 
    wrap: 72
---

# Proposal

## Research topic

This project discovers the relationship between the Federal Funds
Effective Rate（also known as the US interest rate), Overnight Reverse
Repurchase Agreements, 10-Year Treasury Constant Maturity Minus 2-Year
Treasury Constant Maturity, S&P 500, and the Nominal Broad U.S. Dollar
Index. The Federal Funds Effective Rate is a worldwide focused economic
indicator. The increase of the US interest rate may lead to the inflow
of capital into the US, therefore foreign countries monitor and forecast
the movements of the US Federal Funds rate in order to be prepared for
the inflow and outflow of capital in their own countries in order to
stabilize their economy. Also, the modification of the Federal Funds
Rate may impact the capital markets' view about the future economy,
therefore it could impact other economic indicators and ultimately
impact our lives. We listed a few key economic indicators that might be
impacted by the Federal Funds Rate and we aim to discover its impacts on
these indicators and have some sensibility about the economic world.

## Data Source

Our data is from the Federal Reserve Bank of St. Louis's economics
research database:<https://fred.stlouisfed.org/>, we will provide
detailed data sources below for each parameter.

**Federal Funds Effective Rate**:
<https://fred.stlouisfed.org/series/DFF>: Description: the Federal Funds
Effective Rate is the interest rate at which depository institutions
trade federal funds(balances held at Federal Reserve Banks) with each
other overnight. When a depository institution has surplus balances in
its reserve account, it lends to other banks in need of larger balances.
In simpler terms, a bank with excess cash, which is often referred to as
liquidity, will lend to another bank that needs to quickly raise
liquidity. The rate that the borrowing institution pays to the lending
institution is determined between the two banks; the weighted average
rate for all of these types of negotiations is called the effective
federal funds rate. The effective federal funds rate is essentially
determined by the market but is influenced by the Federal Reserve
through open market operations to reach the federal funds rate target.
The Federal Open Market Committee (FOMC) meets eight times a year to
determine the federal fund's target rate. The data is collected on a
7-day frequency and not seasonally adjusted. The data is a percent
number, and we are preparing to import CSV data downloaded from the
link.

**Overnight Reverse Repurchase Agreements**: Treasury Securities Sold by
the Federal Reserve in the Temporary Open Market
Operations：<https://fred.stlouisfed.org/series/RRPONTSYD> Description:
A reverse repurchase agreement (known as reverse repo or RRP) is a
transaction in which the New York Fed under the authorization and
direction of the Federal Open Market Committee sells a security to an
eligible counterparty with an agreement to repurchase that same security
at a specified price at a specific time in the future. For these
transactions, eligible securities are U.S. Treasury instruments, federal
agency debt, and mortgage-backed securities issued or fully guaranteed
by federal agencies. The data is collected on a daily frequency and not
seasonally adjusted. The data is in billions of dollars and we are
preparing to import CSV data downloaded from the link.

**10-Year Treasury Constant Maturity Minus 2-Year Treasury Constant
Maturity**: <https://fred.stlouisfed.org/series/T10Y2Y> Description:
This data series is calculated by subtracting the 2-Year Treasury
Constant Maturity from the 10-Year Treasury Constant Maturity rate. This
number reflects the market's emotion towards the economy. When the
number goes up, which means the difference spreads wider, the market
tends to prefer the 10-Year Treasury relative to the 2-Year Treasury
rate, this indicates that the market is not confident in investing in
the short term, therefore they choose to invest long term, which means
the short term economy may go down. The data is collected on a daily
frequency, it is a percent number and not seasonally adjusted. We are
preparing to import CSV data downloaded from the link.

**S&P 500**: <https://fred.stlouisfed.org/series/SP500> The S&P 500
represent the daily index value at market close. The market typically
closes at 4 PM ET, except for holidays when it sometimes closes early.
The index includes 500 leading companies in leading industries of the
U.S. economy, which are publicly held on either the NYSE or NASDAQ and
covers 75% of U.S. equities. Since this is a price index and not a total
return index, the S&P 500 index here does not contain dividends. It is
the representation of the US equities market. The data is collected on
the daily frequency and it is an index number without being seasonally
adjusted. We are preparing to import CSV data downloaded from the link.

## Data availability

<https://fred.stlouisfed.org/>

<https://fred.stlouisfed.org/series/DFF>

<https://fred.stlouisfed.org/series/RRPONTSYD>

<https://fred.stlouisfed.org/series/T10Y2Y>

<https://fred.stlouisfed.org/series/SP500>

<https://fred.stlouisfed.org/series/DTWEXBGS>
